### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ulivz** [rich-lab/blog#3]
## 2020

- [x] #5 新增 Translations 专栏（@ulivz）
- [x] #6 集成 GA（@ulivz）
- [ ] #7 post 格式规范 (@jothy1023 )
- [ ] #8 新增 Team 专区（@djyde ）
- [x] #11 增加 RSS
- [x] #12 增加 Sitemap
- [ ] 新增页面底部的智能推荐组件
- [ ] 确定新博文提交流程
- [ ] 首页改版，增加统一 Footer
- [ ] 迁移 RichLab 知乎现有的博客
- [ ] 增加友情链接
- [ ] 新增 Photography 专栏
- [ ] 官网的内网版本

**Comment by SMbey0nd** [comment]
考虑下内网版本的规划吧，内网可以有更多技术产品的展示和更丰富的信息😀

**Comment by SMbey0nd** [comment]
Team 专区准备放啥内容？跟 Photography 的主要区别是？
